### ISSUE TITLE
index oob in crates/hir_ty/src/ctx.rs `replace_weak_tys`

### ISSUE THREAD

**Issue by lenawanel** [capy-language/capy#11]
input: 
```
dqlf := Person { a 
tc::}/)-2extePstrE

    str^ = "Helko, S7 "Hello, Sailor!";

    Person :: struct {
        y: Vector3,
    }
};

Vector3 :: distinct [3] i32; 
```

barck trace:
```
// snip
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/alloc/src/vec/mod.rs:2726:9
   6: hir_ty::ctx::<impl hir_ty::InferenceCtx>::replace_weak_tys
             at ./crates/hir_ty/src/ctx.rs:282:49
   7: hir_ty::ctx::<impl hir_ty::InferenceCtx>::infer_expr
             at ./crates/hir_ty/src/ctx.rs:954:21
   8: hir_ty::ctx::<impl hir_ty::InferenceCtx>::infer_expr
             at ./crates/hir_ty/src/ctx.rs:932:30
   9: hir_ty::ctx::<impl hir_ty::InferenceCtx>::finish_body_unknown
             at ./crates/hir_ty/src/ctx.rs:110:9
  10: hir_ty::InferenceCtx::get_global_signature
             at ./crates/hir_ty/src/lib.rs:318:26
  11: hir_ty::InferenceCtx::finish
             at ./crates/hir_ty/src/lib.rs:271:21
  12: capy::compile_file
             at ./crates/capy/src/main.rs:264:39
  13: capy::main
  // snip
  ```

**Comment by lenawanel** [comment]
doesn't reproduce anymore

**Comment by lenawanel** [comment]
still persists :cry: . updated input:
```capy
u32 struct { x distinct u32 = u32 = * { d = u32 } }

{ usize - { d { d  } c != ^ d {
```

**Comment by NotAFlyingGoose** [comment]
Nooo!

**Comment by NotAFlyingGoose** [comment]
@lenawanel, interestingly #14 causes a different error
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates\hir_ty\src\ctx.rs:182:25
```

**Comment by NotAFlyingGoose** [comment]
The original input does not oob in the lastest commit. I'm gonna close this issue an reopen a new one since this is a different input and error message entirely.
