### ISSUE TITLE
`Option::unwrap()` on a `None` in `replace_weak_tys`

### ISSUE THREAD

**Issue by NotAFlyingGoose** [capy-language/capy#15]
input
```
u32 struct { x distinct u32 = u32 = * { d = u32 } }

{ usize - { d { d  } c != ^ d {
```
panics with
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates\hir_ty\src\ctx.rs:182:25
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\std\src\panicking.rs:593
   1: core::panicking::panic_fmt
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:67
   2: core::panicking::panic
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library\core\src\panicking.rs:117
   3: enum2$<core::option::Option<ref$<internment::intern::Intern<enum2$<hir_ty::resolved_ty::ResolvedTy> > > > >::unwrap<ref$<internment::intern::Intern<enum2$<hir_ty::resolved_ty::Resolved
Ty> > > >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\option.rs:935
   4: la_arena::map::impl$1::index<internment::intern::Intern<enum2$<hir_ty::resolved_ty::ResolvedTy> >,enum2$<hir::body::Expr> >
             at C:\Users\goose\.cargo\registry\src\index.crates.io-6f17d22bba15001f\la-arena-0.2.1\src\map.rs:61
   5: hir_ty::InferenceCtx::replace_weak_tys
             at .\crates\hir_ty\src\ctx.rs:182
   6: hir_ty::InferenceCtx::replace_weak_tys
             at .\crates\hir_ty\src\ctx.rs:282
   7: hir_ty::InferenceCtx::replace_weak_tys
             at .\crates\hir_ty\src\ctx.rs:246
   8: hir_ty::InferenceCtx::infer_expr
             at .\crates\hir_ty\src\ctx.rs:941
   9: hir_ty::InferenceCtx::infer_stmt
             at .\crates\hir_ty\src\ctx.rs:445
  10: hir_ty::InferenceCtx::infer_expr
             at .\crates\hir_ty\src\ctx.rs:980
  11: hir_ty::InferenceCtx::infer_expr
             at .\crates\hir_ty\src\ctx.rs:960
  12: hir_ty::InferenceCtx::finish_body_unknown
             at .\crates\hir_ty\src\ctx.rs:108
  13: hir_ty::InferenceCtx::get_global_signature
             at .\crates\hir_ty\src\lib.rs:318
  14: hir_ty::InferenceCtx::finish
             at .\crates\hir_ty\src\lib.rs:271
  15: capy::compile_file
             at .\crates\capy\src\main.rs:264
  16: capy::main
             at .\crates\capy\src\main.rs:112
  17: core::ops::function::FnOnce::call_once<enum2$<core::result::Result<tuple$<>,std::io::error::Error> > (*)(),tuple$<> >
             at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be\library\core\src\ops\function.rs:250
```

**Comment by lenawanel** [comment]
also forgot to mention this in the original issue, and don't have the crashing inputs with me rn, but a similar crash can also happen in line 280 in the same function

**Comment by NotAFlyingGoose** [comment]
@lenawanel I'm fixing this issue, what are the alternate inputs?

**Comment by lenawanel** [comment]
@NotAFlyingGoose here is the crashing input: 
```
:Sailor()usize: "Gs::1fp = "Helko, S= "Hello, Sailor!";

    Person :: struct {
    y: Vector3,
};

Vector3 :: distinct [3] i3:;las-f<= Person{e->z,zn:n:2&istinct [3] i32;::1}
```
this crashes with a different error:
`index out of bounds: the len is 1 but the index is 1`
so it might be a different issue.
stack backtrace 
```
   2: core::panicking::panic_bounds_check
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/panicking.rs:180:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/slice/index.rs:261:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/030e4d382f1df30240408540f25cd1ccc8dbbf50/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
   6: hir_ty::ctx::<impl hir_ty::InferenceCtx>::replace_weak_tys
             at ./crates/hir_ty/src/ctx.rs:280:49
   7: hir_ty::ctx::<impl hir_ty::InferenceCtx>::infer_expr
             at ./crates/hir_ty/src/ctx.rs:941:21
   8: hir_ty::ctx::<impl hir_ty::InferenceCtx>::finish_body_unknown
             at ./crates/hir_ty/src/ctx.rs:108:9
   9: hir_ty::InferenceCtx::get_global_signature
             at ./crates/hir_ty/src/lib.rs:318:26
  10: hir_ty::InferenceCtx::finish
             at ./crates/hir_ty/src/lib.rs:271:21
  11: capy::compile_file
```

**Comment by NotAFlyingGoose** [comment]
@lenawanel Does this still crash as of the latest commit?

**Comment by lenawanel** [comment]
> @lenawanel Does this still crash as of the latest commit?

no :tada:
